function F = bgvm(x1, x2, sin_y, cos_y, u, Kcc, Kss, Kcs, w_true)
% bgvm
% Calculates the normalising constant for a bivariate GvM factor to check
% against EP implementation.

        % Linear 
        linear = u(1) .* (cos_y(1) .* cos(x1) + ...
                               sin_y(1) .* sin(x1)) + ...
                 u(2) .* (cos_y(2) .* cos(x2) + ...
                               sin_y(2) .* sin(x2));

        % Squared cosine term
        cos_sq = Kcc(1,1) .* cos(x1) .^ 2 + ...
                 2. * Kcc(2,1) .* cos(x1) .* cos(x2) + ...
                 Kcc(2,2) .* cos(x2) .^ 2;

        % Squared sine term
        sin_sq = Kss(1,1) .* sin(x1) .^ 2 + ...
                 2. * Kss(2,1) .* sin(x1) .* sin(x2) + ...
                 Kss(2,2) .* sin(x2) .^ 2;     

        % Cross sine and cosine terms
        cos_sin = Kcs(1,1) .* cos(x1) .* sin(x1) + ...
                  Kcs(1,2) .* cos(x1) .* sin(x2) + ...
                  Kcs(2,1) .* cos(x2) .* sin(x1) + ...
                  Kcs(2,2) .* cos(x2) .* sin(x2);

        F = exp(linear + cos_sq + sin_sq + cos_sin - w_true);
end